### ISSUE TITLE
CSRF validation fails on account signup

### ISSUE THREAD

**Issue by skolsuper** [rossp/djangosites.org#3]
Submitting the form at http://djangosites.org/accounts/signup/ results in a 403 with CSRF validation failed message

**Comment by rossp** [comment]
Thank you - looks like it works correctly via SSL; I need to figure out why CloudFlare isn't redirecting all requests to be https-only.

**Comment by rossp** [comment]
Fixed the redirect rules - thank you for reporting this.

**Comment by skolsuper** [comment]
You're welcome, thanks for fixing :+1:
