### ISSUE TITLE
Question: will you be open for collaboration site redesign and code update?

### ISSUE THREAD

**Issue by n3storm** [rossp/djangosites.org#4]
We are a micro company who has developed a Django CMS for our customers. We would like to refer new customers to a site where they can see how cool django can be, plus promoting Django to a wider developer audience.

We would like to help redesigning djangosites.org with current visual standards, responsiveness, and if needed work on code update to Django version =< 1.8

Cheers

**Comment by rossp** [comment]
Thank you for your note. We have a new template that will go live soon but otherwise I am not looking to make any other changes to the site at this stage as I don't feel that DjangoSites is the best place for a wider developer audience - it is intended to be a simple listing of websites.
